sitename: "Spring Boot Guides"
baseURL: "https://blog.florian-moehle.de/"
languageCode: en-us
title: "Spring Boot Guides"
author: Florian M.

enableRobotsTXT: true

params:
  sitename: "Spring Boot Guides"
  copyrights: Florian M.

theme: kaslaanka

menu:
  primary:
    - name: Home
      url: /
      weight: 1