sitename: "Spring Boot Guides"
baseURL: "https://blog.florian-moehle.de"
languageCode: en-us
title: "Spring Boot Guides"
author: Florian M.

params:
  sitename: "Spring Boot Guides"
  copyrights: Florian M.

theme: kaslaanka

googleAnalytics: "G-E52YHHLZG3"