sitename: "Spring Boot Quickstart Guides"
baseURL: "https://spring-guides-page.github.io/spring-guides/"
languageCode: en-us
title: "Spring Boot Quickstart Guides"
author: Florian M.

params:
  copyrights: Florian M.

theme: kaslaanka

googleAnalytics: "G-E52YHHLZG3"