sitename: "Spring Boot Guides"
baseURL: "https://blog.florian-moehle.de/"
languageCode: en-us
title: "Spring Boot Guides"
author: Florian M.

params:
  sitename: "Spring Boot Guides"
  copyrights: Florian M.

theme: kaslaanka

menu:
  primary:
    - name: Home
      url: /
      weight: 1
    - name: Personal Website
      url: https://florian-moehle.de
      weight: 2

googleAnalytics: "G-E52YHHLZG3"